name: bubble_tea_cups_5
singular: bubble tea cup
plural: bubble tea cups
physics:
  restitution: 0.0
objects:
  - name: bubble_tea_cup_800g_target
    usd_path: Assets/Object/Rigid/bubble_tea_cup/800g/Aligned.usd
    metadata_path: Assets/Object/Rigid/bubble_tea_cup/800g/metadata.json
  - name: bubble_tea_cup_300g_01
    usd_path: Assets/Object/Rigid/bubble_tea_cup/300g/Aligned.usd
    metadata_path: Assets/Object/Rigid/bubble_tea_cup/300g/metadata.json
  - name: bubble_tea_cup_300g_02
    usd_path: Assets/Object/Rigid/bubble_tea_cup/300g/Aligned.usd
    metadata_path: Assets/Object/Rigid/bubble_tea_cup/300g/metadata.json
  - name: bubble_tea_cup_500g_01
    usd_path: Assets/Object/Rigid/bubble_tea_cup/500g/Aligned.usd
    metadata_path: Assets/Object/Rigid/bubble_tea_cup/500g/metadata.json
  - name: bubble_tea_cup_500g_02
    usd_path: Assets/Object/Rigid/bubble_tea_cup/500g/Aligned.usd
    metadata_path: Assets/Object/Rigid/bubble_tea_cup/500g/metadata.json
